### ISSUE TITLE
unable to rebuild assets

### ISSUE THREAD

**Issue by BasedAl** [Kaplas80/TF3.YakuzaPlugins#9]
i tried to rebuild the assets but i keep getting these errors:

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at TF3.YarhlPlugin.YakuzaCommon.Converters.Par.Writer.Convert(NodeContainerFormat source)
   at Yarhl.FileFormat.ConvertFormat.With(IConverter converter, Object src)
   at TF3.Core.Helpers.YarhlNodeExtension.ApplyChange(Node node, ConverterMetadata metadata, Object[] parameters) in /_/src/Libraries/TF3.Core/Helpers/YarhlNodeExtension.cs:line 94
   at TF3.Core.Helpers.YarhlNodeExtension.Transform(Node node, List`1 converters, List`1 parameters) in /_/src/Libraries/TF3.Core/Helpers/YarhlNodeExtension.cs:line 69
   at TF3.Core.GameScript.WriteContainers(List`1 containers, Node parent) in /_/src/Libraries/TF3.Core/GameScript.cs:line 266
   at TF3.Core.GameScript.Rebuild(String gamePath, String translationPath, String outputPath) in /_/src/Libraries/TF3.Core/GameScript.cs:line 201
   at TF3.CommandLine.Program.Rebuild(RebuildOptions options) in /_/src/Apps/TF3.CommandLine/Program.cs:line 184
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TF3.CommandLine.Program.Main(String[] args) in /_/src/Apps/TF3.CommandLine/Program.cs:line 41

i use the windows ver.

**Comment by Kaplas80** [comment]
Hello!

I need more info to reproduce the problem:

- What game are you translating?
- Have you deleted any file of the extracted assets directory or changed the directory structure after extraction?
- Does it crash when rebuilding the first asset or is it able to process any?
- Is your game modded in some way?
- What is the exact command line you are using?

Note that it works for me, so the more details you give me about the steps you followed until the error occurred, the easier it will be to find it and fix it.
